thumbnizer_default_route:
   path: /
   defaults: { _controller: ThumbnizerProcessingBundle:Processing:index}

thumbnizer_processing_route4:
   path: /{width}/{height}/{effect}/{source}
   defaults: { _controller: ThumbnizerProcessingBundle:Processing:processingWHE}
   requirements:
        width: \d+
        height: \d+
        effect: (grayscale|oldfashioned|sepia|antique|vintage|lomo)
        source: .+

thumbnizer_processing_route1:
   path: /{width}/{height}/{source}
   defaults: { _controller: ThumbnizerProcessingBundle:Processing:processingWH}
   requirements:
        width: \d+
        height: \d+
        source: .+

thumbnizer_processing_route2:
   path: /{percent}/{source}
   defaults: { _controller: ThumbnizerProcessingBundle:Processing:processingP}
   requirements:
        percent: \d+
        source: .+

thumbnizer_processing_route3:
   path: /{dimension}/{value}/{source}
   defaults: { _controller: ThumbnizerProcessingBundle:Processing:processingWHP}
   requirements:
        dimension: width|height
        value: \d+
        source: .+

