thumbnizer_default_route:
   path: /
   defaults: { _controller: ThumbnizerProcessingBundle:Processing:index}

thumbnizer_processing_route1:
   path: /{width}/{height}/{source}
   defaults: { _controller: ThumbnizerProcessingBundle:Processing:processingWH}
   requirements:
        width: \d+
        height: \d+
        source: .+

thumbnizer_processing_route2:
   path: /{percent}/{source}
   defaults: { _controller: ThumbnizerProcessingBundle:Processing:processingP}
   requirements:
        percent: \d+
        source: .+