parameters:
#    thumbnizer_processing.example.class: Thumbnizer\ProcessingBundle\Example

services:
#    thumbnizer_processing.example:
#        class: %thumbnizer_processing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    #thumbnizer_processor:
        #class:	Thumbnizer\ProcessingBundle\ImageProcessor
        #arguments:	[image]